### ISSUE TITLE
Support x86_64

### ISSUE THREAD

**Issue by grrowl** [fabiospampinato/tiny-sqlite3#3]
Any interest in adding support for `sqlite3-linux-x86_64`?

**Comment by fabiospampinato** [comment]
Yeah why not, it's probably worth spending 3 extra MB for that.

The problem is for security reasons I need to compile binaries for linux and mac myself (the one for Windows is officially provided), but I'm on an arm64 computer and that might be tricky to do 🤔 I'm not sure how to do that at the moment.

**Comment by grrowl** [comment]
No worries, I compiled it on my web host which is Ubuntu Server on DigitalOcean. You could spin one up pretty quickly, compile the thing, `scp newhost:/home/root/tiny-sqlite3/resources/binaries/sqlite3-linux-x64 ./` then shut it down within the hour which would cost (at least) $0.00595 😁

Totally understand the security aspect 👍 — I'm not personally blocked on this issue any more.

**Comment by fabiospampinato** [comment]
Closing since for better or for worse I had to change the approach and use better-sqlite3.
